name: Continuous Integration

# Run only on main and feature branches if Python files were changed
on:
  push:
    branches:
      - main
      - 'feature/**'
    # Deactivated for testing
    # paths:
    #   - '**.py'

env:
  PYTHON_IMAGE: 'python:3.12-slim'
  POETRY_VERSION: 2.1.2
  
jobs:
  test-and-check:
    name: Test and Check Python Code
    runs-on: ubuntu-latest
    container: python:3.12-slim # TODO: How to use a variable here?
    env:
      POETRY_HOME: '/opt/poetry'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Poetry
        run: |
          python -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install --no-cache-dir poetry==$POETRY_VERSION
      
      - name: Install Dependencies
        run: |
          cd $GITHUB_WORKSPACE
          $POETRY_HOME/bin/poetry install --no-root --no-interaction --with=dev
      
      - name: Run Pytest
        run: |
          $POETRY_HOME/bin/poetry run pytest tests/ -v

      - name: Run Format Check
        run: |
          $POETRY_HOME/bin/poetry run black --check src/ tests/

      - name: Run Linting
        run: |
          $POETRY_HOME/bin/poetry run mypy src/
      
      - name: Run SAST
        run: |
          $POETRY_HOME/bin/poetry run bandit src/ -r -ll  # Report medium vulnerabilities or higher
  
  scan:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    steps:
      # Build project container image
      # Scan Image with Trivy
      - name: Install Trivy
        run: |
          # According to https://trivy.dev/latest/getting-started/installation/#debianubuntu-official
          # Hint: I'm aware that Trivy has a GitHub Action, this is just for learning purposes
          apt-get update
          apt-get install wget gnupg -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | tee -a /etc/apt/sources.list.d/trivy.list
          apt-get update
          apt-get install trivy
      
      - name: Verify Installations
        run: |
          trivy --version
          docker --version