name: Continuous Integration

# Run only on main and feature branches if Python files were changed
on:
  push:
    branches:
      - main
      - 'feature/**'
    # Deactivated for testing
    # paths:
    #   - '**.py'

env:
  PYTHON_IMAGE: 'python:3.12-slim'
  POETRY_VERSION: 2.1.2
  
jobs:
  # Checkout code
  # Setup environment incl. dev dependencies using poetry
  # Run pytest (and fail if tests fail?)
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container: python:3.12-slim # TODO: How to use a variable here?
    steps:
      - name: Debug information
        run: echo "This job was automatically triggered by commit ${{ github.sha }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Poetry
        run: |
          python -m venv /opt/poetry
          /opt/poetry/bin/pip install --no-cache-dir poetry==$POETRY_VERSION
      
      - name: Install Dependencies
        run: |
          cd $GITHUB_WORKSPACE
          /opt/poetry/bin/poetry install --no-root --no-interaction --with=dev
      
      - name: Run Pytest
        run: |
          poetry run pytest tests/ -v
  
  another-job:
    name: I will eventually be a useful job
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - run: echo "The unit tests were successful!"