name: Continuous Integration

# Run only on main and feature branches if Python files were changed
on:
  push:
    branches:
      - main
      - 'feature/**'
    # Deactivated for testing
    # paths:
    #   - '**.py'

env:
  PYTHON_IMAGE_VERSION: 3.12-slim
  POETRY_VERSION: 2.1.2
  
jobs:
  # Checkout code
  # Setup environment incl. dev dependencies using poetry
  # Run pytest (and fail if tests fail?)
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container: python:${{ env.PYTHON_IMAGE_VERSION }}
    steps:
      - name: Debug information
        run: echo "This job was automatically triggered by commit ${{ github.sha }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python environment
        run: |
          python -m venv /opt/poetry
          /opt/poetry/bin/pip install --no-cache-dir poetry==$POETRY_VERSION
          ls -lisa /
  
  another-job:
    name: I will eventually be a useful job
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - run: echo "The unit tests were successful!"