name: Infrastructure Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tf:
    name: "Run Terraform Code"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Init Terraform CLI
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: |
          terraform init