name: Infrastructure Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - '.github/workflows/infra-pipeline.yaml'
      - 'terraform/**/*'

permissions:
  id-token: write # Needed for Azure CLI Login

jobs:
  run-tf:
    name: "Run Terraform Code"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: c3971fe8-fae4-4df5-91f3-4b2e71078ffe 
          tenant-id: e5f140b4-77b2-48a0-9775-fe7437c50fa6
          subscription-id: 486b8df7-bf37-4b89-a5ee-c43cf5ec2b05

      - name: Init Terraform CLI
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: |
          terraform init